### ISSUE TITLE
failed build

### ISSUE THREAD

**Issue by panique** [bobbymaher/docker-laravel-workers#1]
Hi, this is a good idea, but it cannot run as you have a wrong filename inside:

`ERROR: Service 'php-worker' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder086123312/supervisord-old-worker.conf: no such file or directory`

The filename should be `supervisord.conf`

**Comment by panique** [comment]
The `php-horizon:` also breaks as the container_name needs to be `container_name: php-horizon`, not `php-cron` :)

**Comment by bobbymaher** [comment]
fixed the above 👍
